fieldLayouts:
  3292f836-c3bb-4904-80db-6de3e52ef83d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6547b88b-997e-40c7-b75b-89b612452ad2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68bac844-44db-4e32-aa07-38ce94edeebb # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47919333-915f-494a-8d54-bc9802929ee2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 75ee5271-a253-4efa-9c0d-5777e19a14b3
        userCondition: null
handle: home
hasTitleField: false
name: Home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
