fieldLayouts:
  d6353175-9bf7-4995-a1ae-95afcc63dd2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e4e76882-91a0-43e6-9d4c-38dbb96cf702
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6728c84e-225d-4b26-b7df-a43ef7fe8713
        userCondition: null
handle: newsIndex
hasTitleField: false
name: 'News (Index)'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
