color: orange
fieldLayouts:
  34c2f6f8-9429-42be-9d64-282b3d4bef37:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7498eea7-3740-494e-9ef7-37c622380a85
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bbdb3491-25e4-46d9-b775-74a82d472f3f # Copy
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a83d6e0-f16b-4388-b4b0-257effb6e96a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8d99a5b7-2d31-4a44-99c6-72c6673a6ee2
        userCondition: null
handle: standardCopy
hasTitleField: false
icon: text
name: 'Standard Copy'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
