columnSuffix: null
handle: copy
instructions: null
name: Copy
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: c3deb65d-6a5c-44aa-840e-0850d850f162 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
