name: challenge
type: craftcms
docroot: web
php_version: '8.3'
webserver_type: nginx-fpm
router_http_port: '80'
router_https_port: '443'
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mysql
  version: '8.0'
use_dns_when_possible: true
composer_version: '2'
nodejs_version: '18'
# Vite ports
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5174
    https_port: 5173
